# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_merchant',
            field=models.CharField(default='', max_length=3),
        ),
    ]
