# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_dash', '0002_auto_20180401_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
