# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 19:37
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_dash', '0004_auto_20180402_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
