# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_dash', '0006_auto_20180402_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_summary',
            field=models.CharField(default='No Ad Summary', max_length=255),
        ),
    ]
