# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_dash', '0008_auto_20180403_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_price',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
