# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_dash', '0010_auto_20180421_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
