# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersale',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.AddField(
            model_name='customersale',
            name='checkout_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
