# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-22 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_customersale_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersale',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
